spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # Specify the path where H2 console will be accessible

server:
  max-http-request-header-size: 64KB
  port: 8081